kube-prometheus-stack:
  fullnameOverride: monitoring

  grafana:
    enabled: true
    adminUser: admin
    adminPassword: admin

    service:
      type: ClusterIP
      port: 80

    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - grafana.local
      path: /

    persistence:
      enabled: true
      type: pvc
      size: 2Gi

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 512Mi

  prometheus:
    prometheusSpec:
      retention: 7d
      retentionSize: 4GB

      resources:
        requests:
          cpu: 150m
          memory: 512Mi
        limits:
          memory: 1Gi

      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 8Gi

  alertmanager:
    enabled: true
    alertmanagerSpec:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          memory: 256Mi

      storage:
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi

  prometheusOperator:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 512Mi

  kubeStateMetrics:
    enabled: true

  nodeExporter:
    enabled: true

  defaultRules:
    create: true

  kubeEtcd:
    enabled: false

  kubeControllerManager:
    enabled: false

  kubeScheduler:
    enabled: false