apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami
  namespace: argocd
  finalizers:
    -resources-finalizers.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/l5ti/homelab.git
    targetRevision: main
    path: apps/whoami

  destination:
    server: https://kubernetes.default.svc
    namespace: whoami

  syncPolicy:
    syncOptions:
      - CreateNamespace=true