replicas: 1

adminUser: admin
adminPassword: admin

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - grafana.local
  path: /
  pathType: Prefix

persistence:
  enabled: true
  type: pvc
  size: 2Gi

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 512Mi